name: Build and Deploy
on: push
permissions:
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        with:
          artifact_name: builds/website
          
      
